version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi-web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
     	DATABASE_URL: postgresql://postgres:postgres@db:5432/fastapi_demo
	OPENAI_API_KEY: "cheia_ta_openai"
    volumes:
  postgres_data:
